[project]
name = 'Transparent-Public-Fund-Allocation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.budget-allocation]
path = 'contracts/budget-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.citizen-feedback]
path = 'contracts/citizen-feedback.clar'
clarity_version = 2
epoch = 2.5

[contracts.expense-tracking]
path = 'contracts/expense-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-measurement]
path = 'contracts/performance-measurement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
